source: "./"
theme: jekyll-theme-cayman
collections:
  balls:
    output: true
    permalink: /:collection
  caps:
    output: true
    permalink: /:collection
  coats:
    output: true
    permalink: /:collection
  fur:
    output: true
    permalink: /:collection
  items:
    output: true
    permalink: /:collection
  shoes:
    output: true
    permalink: /:collection
  missions:
    output: true
    permalink: /missions/:slug
