source: "./"
theme: jekyll-theme-cayman
collections:
  shop/balls:
    output: true
  caps:
    output: true
  shop/coats:
    output: true
  shop/fur:
    output: true
  shop/items:
    output: true
  shop/shoes:
    output: true
