source: "./"
theme: jekyll-theme-cayman
collections:
  balls:
    output: true
    path: _shop/_balls
  caps:
    output: true
    path: _shop/_caps
  coats:
    output: true
    path: _shop/_coats
  fur:
    output: true
    path: _shop/_fur
  items:
    output: true
    path: _shop/_items
  shoes:
    output: true
    path: _shop/_shoes
